name: Pull_Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action@2201.0.0
              with:
                  args:
                      pack
              env:
                  WORKING_DIR: ./storageservice
            - name: Ballerina Test
              uses: ballerina-platform/ballerina-action@2201.0.0
              with:
                  args:
                      test 
              env:
                  ACCOUNT_NAME: ${{ secrets.ACCOUNT_NAME }}
                  ACCESS_KEY_OR_SAS: ${{ secrets.ACCESS_KEY_OR_SAS }}
                  WORKING_DIR: ./storageservice
         
